name:                ebnf-extensions
version:             0.1.0.0
github:              "nedervold/ebnf-extensions"
license:             BSD3
author:              "Eric Nedervold"
maintainer:          "nedervoldsoftware@gmail.com"
copyright:           "2019 Eric Nedervold"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Simple extensions to BNF with generators and parsers.
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nedervold/ebnf-extensions#readme>

ghc-options: -Wall -Wcompat

dependencies:
- base >= 4.7 && < 5
- hedgehog
- microlens-th
- parser-combinators

library:
  source-dirs: src

tests:
  ext-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ebnf-extensions
    - hedgehog-classes
    - hspec
    - hspec-megaparsec
    - megaparsec
    - tasty
    - tasty-discover
    - tasty-hspec
